# Cloudflare Pages configuration
name = "burtonupontrentplumbers-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "burton-leads"
database_id = "a68429c4-0c85-4925-b2de-af73050a5ae0"
